import AppKit
@testable import FluidVoice_Debug
import XCTest

/// Verifies that temporary Cmd+V payloads are tagged so clipboard managers exclude them
/// from history while the plain-text representation remains available to the paste target.
@MainActor
final class TypingServiceTransientPasteboardTests: XCTestCase {
    func testTemporaryPasteboardWriteCarriesText() {
        let pasteboard = self.makePasteboard()
        defer { pasteboard.releaseGlobally() }

        XCTAssertTrue(
            SystemPasteboardManager(pasteboard: pasteboard)
                .writeTemporaryText("hello world", sessionID: "session")
        )
        XCTAssertEqual(pasteboard.string(forType: .string), "hello world")
    }

    func testTemporaryPasteboardWriteIsMarkedForClipboardManagers() throws {
        let pasteboard = self.makePasteboard()
        defer { pasteboard.releaseGlobally() }

        XCTAssertTrue(
            SystemPasteboardManager(pasteboard: pasteboard)
                .writeTemporaryText("hello world", sessionID: "session")
        )
        let item = try XCTUnwrap(pasteboard.pasteboardItems?.first)
        let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
        let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
        let types = item.types.map(\.rawValue)
        XCTAssertTrue(
            types.contains(transientType.rawValue),
            "temporary write must be marked Transient so clipboard managers skip it"
        )
        XCTAssertTrue(
            types.contains(autoGeneratedType.rawValue),
            "temporary write must be marked AutoGenerated so clipboard managers skip it"
        )
        XCTAssertEqual(
            item.data(forType: transientType)?.count,
            0
        )
        XCTAssertEqual(
            item.data(forType: autoGeneratedType)?.count,
            0
        )
    }

    func testTemporaryPasteboardWriteCarriesSourceAndSession() throws {
        let pasteboard = self.makePasteboard()
        defer { pasteboard.releaseGlobally() }

        XCTAssertTrue(
            SystemPasteboardManager(pasteboard: pasteboard)
                .writeTemporaryText("hello world", sessionID: "session")
        )
        let item = try XCTUnwrap(pasteboard.pasteboardItems?.first)
        let sourceType = NSPasteboard.PasteboardType("org.nspasteboard.source")
        let sessionType = NSPasteboard.PasteboardType(
            "\(Bundle.main.bundleIdentifier ?? "com.FluidApp.Fluid").PasteSession"
        )
        XCTAssertEqual(item.string(forType: sourceType), Bundle.main.bundleIdentifier ?? "com.FluidApp.Fluid")
        XCTAssertEqual(item.string(forType: sessionType), "session")
    }

    func testTemporaryPasteboardWriteIsNotMarkedConcealed() throws {
        let pasteboard = self.makePasteboard()
        defer { pasteboard.releaseGlobally() }

        XCTAssertTrue(
            SystemPasteboardManager(pasteboard: pasteboard)
                .writeTemporaryText("hello world", sessionID: "session")
        )
        let item = try XCTUnwrap(pasteboard.pasteboardItems?.first)
        let types = item.types.map(\.rawValue)
        XCTAssertFalse(
            types.contains("org.nspasteboard.ConcealedType"),
            "ConcealedType signals sensitive content and must not be applied to a transcript"
        )
    }

    func testRecoveryActivationDoesNotRaiseAllWindowsOfTargetApp() {
        // Issue #748: recovery must NOT raise every window of the target app.
        let options = TypingService.recoveryActivationOptions

        XCTAssertTrue(
            options.contains(.activateIgnoringOtherApps),
            "recovery must still activate the target app and bring it forward"
        )
        XCTAssertFalse(
            options.contains(.activateAllWindows),
            "Recovery must not raise every window of the target app (issue #748)"
        )
    }

    func testIntentionalClipboardWriteIsHistoryVisible() throws {
        let pasteboard = self.makePasteboard()
        defer { pasteboard.releaseGlobally() }

        XCTAssertTrue(SystemPasteboardManager(pasteboard: pasteboard).writeIntentionalText("keep me"))

        let item = try XCTUnwrap(pasteboard.pasteboardItems?.first)
        let types = item.types.map(\.rawValue)
        XCTAssertEqual(item.string(forType: .string), "keep me")
        XCTAssertFalse(types.contains("org.nspasteboard.TransientType"))
        XCTAssertFalse(types.contains("org.nspasteboard.AutoGeneratedType"))
        XCTAssertFalse(types.contains("org.nspasteboard.ConcealedType"))
        XCTAssertFalse(types.contains { $0.hasSuffix(".PasteSession") })
    }

    func testSnapshotRestoresEveryRepresentation() throws {
        let pasteboard = self.makePasteboard()
        defer { pasteboard.releaseGlobally() }
        let customType = NSPasteboard.PasteboardType("com.fluidvoice.tests.custom")
        let customData = Data([0x01, 0x02, 0x03])
        let originalItem = NSPasteboardItem()
        XCTAssertTrue(originalItem.setString("original", forType: .string))
        XCTAssertTrue(originalItem.setData(customData, forType: customType))
        let secondItem = NSPasteboardItem()
        XCTAssertTrue(secondItem.setString("second", forType: .string))
        XCTAssertTrue(pasteboard.writeObjects([originalItem, secondItem]))

        let manager = SystemPasteboardManager(pasteboard: pasteboard)
        let snapshot = try XCTUnwrap(manager.captureBoundedSnapshot())
        XCTAssertTrue(manager.writeTemporaryText("temporary", sessionID: "session"))
        XCTAssertTrue(manager.restore(snapshot))

        let restoredItems = try XCTUnwrap(pasteboard.pasteboardItems)
        XCTAssertEqual(restoredItems.count, 2)
        let restoredItem = restoredItems[0]
        XCTAssertEqual(restoredItem.string(forType: .string), "original")
        XCTAssertEqual(restoredItem.data(forType: customType), customData)
        XCTAssertEqual(restoredItems[1].string(forType: .string), "second")
    }

    func testOversizedSnapshotFailsWithoutChangingPasteboard() {
        let pasteboard = self.makePasteboard()
        defer { pasteboard.releaseGlobally() }
        let customType = NSPasteboard.PasteboardType("com.fluidvoice.tests.oversized")
        let originalData = Data(
            repeating: 0xab,
            count: SystemPasteboardManager.maximumRepresentationBytes + 1
        )
        let originalItem = NSPasteboardItem()
        XCTAssertTrue(originalItem.setData(originalData, forType: customType))
        XCTAssertTrue(pasteboard.writeObjects([originalItem]))
        let changeCount = pasteboard.changeCount

        XCTAssertNil(SystemPasteboardManager(pasteboard: pasteboard).captureBoundedSnapshot())

        XCTAssertEqual(pasteboard.changeCount, changeCount)
        XCTAssertEqual(pasteboard.data(forType: customType), originalData)
    }

    private func makePasteboard() -> NSPasteboard {
        let name = NSPasteboard.Name("com.fluidvoice.tests.transient.\(UUID().uuidString)")
        let pasteboard = NSPasteboard(name: name)
        pasteboard.clearContents()
        return pasteboard
    }
}
