import AppKit
import Foundation

enum TextDeliveryFailure: String, Equatable {
    case emptyText = "empty_text"
    case accessibilityNotTrusted = "accessibility_not_trusted"
    case clipboardSnapshotFailed = "clipboard_snapshot_failed"
    case clipboardWriteFailed = "clipboard_write_failed"
    case pasteCommandFailed = "paste_command_failed"
    case targetUnavailable = "target_unavailable"
    case targetRestoreFailed = "target_restore_failed"
}

enum TextDeliveryResult: Equatable {
    case commandPosted
    case recoverableFailure(TextDeliveryFailure)

    var wasDispatched: Bool {
        self == .commandPosted
    }
}

struct PasteboardSnapshot: Equatable {
    struct Item: Equatable {
        let representations: [String: Data]
    }

    let items: [Item]
}

@MainActor
protocol PasteboardManaging: AnyObject {
    func captureBoundedSnapshot() -> PasteboardSnapshot?
    func writeTemporaryText(_ text: String, sessionID: String) -> Bool
    func writeIntentionalText(_ text: String) -> Bool
    func isOwned(sessionID: String, expectedText: String) -> Bool
    func restore(_ snapshot: PasteboardSnapshot) -> Bool
}

@MainActor
protocol PasteCommandPosting: AnyObject {
    func postGlobalPasteCommand() async -> Bool
}

@MainActor
final class SystemPasteboardManager: PasteboardManaging {
    private static let sourceType = NSPasteboard.PasteboardType("org.nspasteboard.source")
    private static let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    private static let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
    private static let sessionType = NSPasteboard.PasteboardType(
        "\(Bundle.main.bundleIdentifier ?? "com.FluidApp.Fluid").PasteSession"
    )
    static let maximumRepresentationBytes = 2 * 1024 * 1024
    static let maximumSnapshotBytes = 8 * 1024 * 1024
    static let maximumItems = 100

    private let pasteboard: NSPasteboard

    init(pasteboard: NSPasteboard = .general) {
        self.pasteboard = pasteboard
    }

    func captureBoundedSnapshot() -> PasteboardSnapshot? {
        var totalBytes = 0
        let sourceItems = self.pasteboard.pasteboardItems ?? []
        guard sourceItems.count <= Self.maximumItems else {
            self.logSnapshotFailure(reason: "too_many_items", itemCount: sourceItems.count, totalBytes: totalBytes)
            return nil
        }

        var items: [PasteboardSnapshot.Item] = []
        for sourceItem in sourceItems {
            guard !sourceItem.types.isEmpty else {
                self.logSnapshotFailure(reason: "empty_item", itemCount: sourceItems.count, totalBytes: totalBytes)
                return nil
            }

            var representations: [String: Data] = [:]
            for type in sourceItem.types {
                guard let data = sourceItem.data(forType: type) else {
                    self.logSnapshotFailure(
                        reason: "unavailable_representation",
                        itemCount: sourceItems.count,
                        totalBytes: totalBytes,
                        type: type
                    )
                    return nil
                }
                guard data.count <= Self.maximumRepresentationBytes else {
                    self.logSnapshotFailure(
                        reason: "representation_too_large",
                        itemCount: sourceItems.count,
                        totalBytes: totalBytes,
                        type: type
                    )
                    return nil
                }
                guard data.count <= Self.maximumSnapshotBytes - totalBytes else {
                    self.logSnapshotFailure(
                        reason: "snapshot_too_large",
                        itemCount: sourceItems.count,
                        totalBytes: totalBytes,
                        type: type
                    )
                    return nil
                }
                representations[type.rawValue] = data
                totalBytes += data.count
            }
            items.append(PasteboardSnapshot.Item(representations: representations))
        }

        DebugLogger.shared.benchmark(
            "TYPING_BENCH",
            message: "clipboard_snapshot_complete items=\(items.count) bytes=\(totalBytes)",
            source: "TypingBenchmark"
        )
        return PasteboardSnapshot(items: items)
    }

    func writeTemporaryText(_ text: String, sessionID: String) -> Bool {
        let item = NSPasteboardItem()
        guard item.setString(text, forType: .string),
              item.setString(Bundle.main.bundleIdentifier ?? "com.FluidApp.Fluid", forType: Self.sourceType),
              item.setData(Data(), forType: Self.transientType),
              item.setData(Data(), forType: Self.autoGeneratedType),
              item.setString(sessionID, forType: Self.sessionType)
        else {
            return false
        }

        self.pasteboard.clearContents()
        return self.pasteboard.writeObjects([item]) && self.isOwned(sessionID: sessionID, expectedText: text)
    }

    func writeIntentionalText(_ text: String) -> Bool {
        let item = NSPasteboardItem()
        guard item.setString(text, forType: .string) else { return false }

        self.pasteboard.clearContents()
        return self.pasteboard.writeObjects([item]) && self.pasteboard.string(forType: .string) == text
    }

    func isOwned(sessionID: String, expectedText: String) -> Bool {
        self.pasteboard.string(forType: .string) == expectedText &&
            self.pasteboard.string(forType: Self.sessionType) == sessionID
    }

    func restore(_ snapshot: PasteboardSnapshot) -> Bool {
        var items: [NSPasteboardItem] = []
        for snapshotItem in snapshot.items {
            let item = NSPasteboardItem()
            for (rawType, data) in snapshotItem.representations {
                guard item.setData(data, forType: NSPasteboard.PasteboardType(rawType)) else {
                    return false
                }
            }
            items.append(item)
        }

        self.pasteboard.clearContents()
        return items.isEmpty || self.pasteboard.writeObjects(items)
    }

    private func logSnapshotFailure(
        reason: String,
        itemCount: Int,
        totalBytes: Int,
        type: NSPasteboard.PasteboardType? = nil
    ) {
        DebugLogger.shared.benchmark(
            "TYPING_BENCH",
            message: "clipboard_snapshot_failed reason=\(reason) items=\(itemCount) bytes=\(totalBytes) type=\(type?.rawValue ?? "nil")",
            source: "TypingBenchmark"
        )
    }
}

@MainActor
final class SystemPasteCommandPoster: PasteCommandPosting {
    private static let commandKeyCode: CGKeyCode = 0x37
    private static let vKeyCode: CGKeyCode = 0x09
    private nonisolated static let eventDelayNanoseconds: UInt64 = 10_000_000

    func postGlobalPasteCommand() async -> Bool {
        guard AXIsProcessTrusted() else { return false }

        let source = CGEventSource(stateID: .privateState)
        guard let commandDown = CGEvent(
            keyboardEventSource: source,
            virtualKey: Self.commandKeyCode,
            keyDown: true
        ), let vDown = CGEvent(
            keyboardEventSource: source,
            virtualKey: Self.vKeyCode,
            keyDown: true
        ), let vUp = CGEvent(
            keyboardEventSource: source,
            virtualKey: Self.vKeyCode,
            keyDown: false
        ), let commandUp = CGEvent(
            keyboardEventSource: source,
            virtualKey: Self.commandKeyCode,
            keyDown: false
        ) else {
            return false
        }

        commandDown.flags = .maskCommand
        vDown.flags = .maskCommand
        vUp.flags = .maskCommand

        commandDown.post(tap: .cghidEventTap)
        await self.pauseBetweenEvents()
        vDown.post(tap: .cghidEventTap)
        await self.pauseBetweenEvents()
        vUp.post(tap: .cghidEventTap)
        await self.pauseBetweenEvents()
        commandUp.post(tap: .cghidEventTap)
        return true
    }

    private func pauseBetweenEvents() async {
        // Always finish posting the key-up events, even if the calling task was cancelled.
        try? await Task.sleep(nanoseconds: Self.eventDelayNanoseconds)
    }
}

@MainActor
final class PasteDeliveryCoordinator {
    static let shared = PasteDeliveryCoordinator()
    nonisolated static let defaultSettlementDelayNanoseconds: UInt64 = 1_500_000_000

    private struct ClipboardLease {
        let originalSnapshot: PasteboardSnapshot
        let sessionID: String
        let text: String
        let generation: UInt64
        let shouldKeepTranscript: Bool
        var settlementTask: Task<Void, Never>?
    }

    private let pasteboard: PasteboardManaging
    private let commandPoster: PasteCommandPosting
    private let settlementDelayNanoseconds: UInt64
    private var generation: UInt64 = 0
    private var lease: ClipboardLease?
    private var isDelivering = false
    private var deliveryWaiters: [CheckedContinuation<Void, Never>] = []

    init(
        pasteboard: PasteboardManaging? = nil,
        commandPoster: PasteCommandPosting? = nil,
        settlementDelayNanoseconds: UInt64 = PasteDeliveryCoordinator.defaultSettlementDelayNanoseconds
    ) {
        self.pasteboard = pasteboard ?? SystemPasteboardManager()
        self.commandPoster = commandPoster ?? SystemPasteCommandPoster()
        self.settlementDelayNanoseconds = settlementDelayNanoseconds
    }

    func deliver(
        _ text: String,
        preserveTranscriptOnClipboard: Bool
    ) async -> TextDeliveryResult {
        await self.acquireDeliverySlot()
        defer { self.releaseDeliverySlot() }

        let startedAt = ProcessInfo.processInfo.systemUptime
        self.generation &+= 1
        let generation = self.generation
        self.lease?.settlementTask?.cancel()

        let originalSnapshot = self.captureOriginalSnapshotForNextDelivery()
        self.lease = nil

        guard let originalSnapshot else {
            self.log("delivery_failed generation=\(generation) reason=clipboard_snapshot_failed")
            return .recoverableFailure(.clipboardSnapshotFailed)
        }

        let sessionID = UUID().uuidString
        let writeStartedAt = ProcessInfo.processInfo.systemUptime
        guard self.pasteboard.writeTemporaryText(text, sessionID: sessionID) else {
            self.restoreAfterFailure(originalSnapshot, generation: generation, reason: "clipboard_write_failed")
            self.log("delivery_failed generation=\(generation) reason=clipboard_write_failed")
            return .recoverableFailure(.clipboardWriteFailed)
        }
        self.log(
            "clipboard_write generation=\(generation) elapsedMs=\(Self.elapsedMs(since: writeStartedAt))"
        )

        guard await self.commandPoster.postGlobalPasteCommand() else {
            self.restoreAfterFailure(originalSnapshot, generation: generation, reason: "paste_command_failed")
            self.log("delivery_failed generation=\(generation) reason=paste_command_failed")
            return .recoverableFailure(.pasteCommandFailed)
        }

        self.log(
            "command_posted generation=\(generation) totalMs=\(Self.elapsedMs(since: startedAt))"
        )

        self.lease = ClipboardLease(
            originalSnapshot: originalSnapshot,
            sessionID: sessionID,
            text: text,
            generation: generation,
            shouldKeepTranscript: preserveTranscriptOnClipboard,
            settlementTask: nil
        )
        self.scheduleSettlement(sessionID: sessionID, generation: generation)
        return .commandPosted
    }

    private func acquireDeliverySlot() async {
        guard self.isDelivering else {
            self.isDelivering = true
            return
        }

        await withCheckedContinuation { continuation in
            self.deliveryWaiters.append(continuation)
        }
    }

    private func releaseDeliverySlot() {
        guard !self.deliveryWaiters.isEmpty else {
            self.isDelivering = false
            return
        }

        self.deliveryWaiters.removeFirst().resume()
    }

    func runPendingSettlementForTesting() {
        guard let lease = self.lease else { return }
        lease.settlementTask?.cancel()
        self.settleIfCurrent(sessionID: lease.sessionID, generation: lease.generation)
    }

    private func scheduleSettlement(sessionID: String, generation: UInt64) {
        let settlementDelayNanoseconds = self.settlementDelayNanoseconds
        let task = Task { @MainActor [weak self] in
            try? await Task.sleep(nanoseconds: settlementDelayNanoseconds)
            guard !Task.isCancelled else { return }
            self?.settleIfCurrent(sessionID: sessionID, generation: generation)
        }
        self.lease?.settlementTask = task
        self.log("settlement_scheduled generation=\(generation) delayMs=\(settlementDelayNanoseconds / 1_000_000)")
    }

    private func settleIfCurrent(sessionID: String, generation: UInt64) {
        guard let lease = self.lease,
              lease.generation == generation,
              lease.sessionID == sessionID
        else {
            self.log("settlement_skipped generation=\(generation) reason=stale_generation")
            return
        }

        self.lease = nil
        guard self.pasteboard.isOwned(sessionID: sessionID, expectedText: lease.text) else {
            self.log("settlement_skipped generation=\(generation) reason=clipboard_changed")
            return
        }

        if lease.shouldKeepTranscript {
            let didWrite = self.pasteboard.writeIntentionalText(lease.text)
            self.log("intentional_copy_settled generation=\(generation) success=\(didWrite)")
        } else {
            let didRestore = self.pasteboard.restore(lease.originalSnapshot)
            self.log("restore_completed generation=\(generation) success=\(didRestore)")
        }
    }

    private func captureOriginalSnapshotForNextDelivery() -> PasteboardSnapshot? {
        if let lease = self.lease,
           self.pasteboard.isOwned(sessionID: lease.sessionID, expectedText: lease.text)
        {
            return lease.originalSnapshot
        }
        return self.pasteboard.captureBoundedSnapshot()
    }

    private func restoreAfterFailure(
        _ snapshot: PasteboardSnapshot,
        generation: UInt64,
        reason: String
    ) {
        let didRestore = self.pasteboard.restore(snapshot)
        self.log("failure_restore generation=\(generation) reason=\(reason) success=\(didRestore)")
    }

    private func log(_ message: String) {
        DebugLogger.shared.benchmark("TYPING_BENCH", message: message, source: "TypingBenchmark")
    }

    private static func elapsedMs(since start: TimeInterval) -> Int {
        Int(((ProcessInfo.processInfo.systemUptime - start) * 1000).rounded())
    }
}
